services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
  
  service1:
    build: ./backend/helloService
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
  
  service2:
    build: ./backend/profileService
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production